# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3082774ebc7f4a3cf30ef993034509b0e2b0ed7507981c681b3f6fac25466bb2da6df78cfe8f9be46ff3c48a1a695bbb2e4bb05a814c21b021c0cc7437d8000


test:
  secret_key_base: f7344a3e190bbad26a0400fe7aad3bd200ef72b08af9f82bb922c6cfa95e739705cec87decd5865d6148c9bf25b446389f18aed8c84b5d8e9b5b8c4ef9ef5518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

